### ISSUE TITLE
Hello, I would like to ask, “This package implements ‘Federboost’ from Tian et al ” Which article does ‘Federboost’ come from?

### ISSUE THREAD

**Issue by xwzhang12** [Jaap-Meerhof/Federated_XGBoost_Python#2]

**Comment by Jaap-Meerhof** [comment]
Tian, Z., Zhang, R., Hou, X., Liu, J., & Ren, K. (2020). Federboost: Private federated learning for gbdt. arXiv preprint arXiv:2011.02796.

https://arxiv.org/abs/2011.02796

Thank you for taking interest!

**Comment by Jaap-Meerhof** [comment]
Its just doing Horizontal Federated Learning more securely by adding secure aggregation at the part where the gradients and hessians of different parties needs to be aggregated
